#!/bin/bash
source config.sh
cd $bin_test_dir
$RM
gpu=true
file_name=`basename $0`
name_of_algorithm="hyk_sort"
number_process=1
data_zise=$[100 * number_process]
foo=$[n_cores / np_on_each_node]

echo "****************Running file $file_name*********************" >> $stdout_file
echo "************************************************************" >> $stdout_file
echo ""  >> $stdout_file
while getopts "a:g:" opt; do
  case $opt in
    g)
      gpu=$OPTARG >&2
      ;;
    a)
      name_of_algorithm=$OPTARG >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

host=${list_hosts[0]}

./test_thrust_host_vector -d -e .txt -t long $number_process $data_zise$type_size $gen_data_dir 1>> $stdout_file 2>> $error_file

mpirun -np $number_process $host_tag $host ./test_thrust_host_vector -a $name_of_algorithm -n $foo -e .txt -g true -k 16 -t long $gen_data_dir 1>> $stdout_file 2>> $error_file


result=$?

if [ $result == 0 ]
then
  notification="$file_name 's success"
  echo $notification >> $result_file
  exit 0
else
  notification="$file_name 's failure"
  echo $notification >> $result_file
    echo "******************Finished $file_name*********************" >> $error_file
  echo "***********************************************************" >> $error_file

  exit 1
fi
