#!/bin/bash
source config.sh
cd $bin_test_dir
$RM
gpu=true
file_name=`basename $0`
name_of_algorithm="hyk_sort"
number_node=4
process_per_node=1
data_per_process=3072
data_size=$[number_node * process_per_node * data_per_process]
foo=$[n_cores / process_per_node]

echo "****************Running file $file_name*********************" >> $stdout_file
echo "************************************************************" >> $stdout_file
echo ""  >> $stdout_file
while getopts "a:g:" opt; do
  case $opt in
    g)
      gpu=$OPTARG >&2
      ;;
    a)
      name_of_algorithm=$OPTARG >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

host=${list_hosts[0]}
for i in {1..3}
do
  host="$host,${list_hosts[i]}"
done

./test_key_value -d -v "ap, a1=1,d=3 : ap, a1=4,d=8 : ap , a1=3, d = 9 : ap, a1=-2, d=4 : ap, a1 = -5, d=11: ap, a1 = 5, d=13 : ap, a1=11, d=4 : ap, a1=3, d=21 : ap, a1=4, d=13" 8 $data_size$type_size $gen_data_dir 1>> $stdout_file 2>> $error_file

mpirun -np 8 $host_tag $host ./test_key_value -a $name_of_algorithm -n $foo -g true -k 8 -v "ap, a1=1,d=3: ap, a1=4,d=8 : ap , a1=3, d = 9: ap, a1=-2, d=4 : ap, a1 = -5, d=11 : ap, a1 = 5, d=13 : ap, a1=11, d=4: ap, a1=3,d=21 : ap, a1=4,d=13" $gen_data_dir 1>> $stdout_file 2>> $error_file

result=$?

if [ $result == 0 ]
then
  notification="$file_name 's success"
  echo $notification >> $result_file
  exit 0
else
  notification="$file_name 's failure"
  echo $notification >> $result_file
    echo "******************Finished $file_name*********************" >> $error_file
  echo "***********************************************************" >> $error_file

  exit 1
fi
