#!/bin/bash
source config.sh
cd $bin_test_dir
$RM
gpu=true
file_name=`basename $0`
name_of_algorithm="hyk_sort"
number_node=
process_per_node=
data_per_process=256
data_size=$[15 * data_per_process]
foo=4

echo "****************Running file $file_name*********************" >> $stdout_file
echo "************************************************************" >> $stdout_file
echo ""  >> $stdout_file
while getopts "a:g:" opt; do
  case $opt in
    g)
      gpu=$OPTARG >&2
      ;;
    a)
      name_of_algorithm=$OPTARG >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

host=${list_hosts[0]}
for i in {1..7}
do
  host="$host,${list_hosts[i]}"
done

./test_key_value -d -v "ap, a1=2, d=2 : log, b = 3" 15 $data_size$type_size $gen_data_dir 1>> $stdout_file 2>> $error_file

mpirun -np 15 $host_tag $host ./test_key_value -a $name_of_algorithm -n $foo -g false -k 8 -v "ap, a1=2, d=2 : log, b = 3" $gen_data_dir 1>> $stdout_file 2>> $error_file

result=$?

if [ $result == 0 ]
then
  notification="$file_name 's success"
  echo $notification >> $result_file
  exit 0
else
  notification="$file_name 's failure"
  echo $notification >> $result_file
    echo "******************Finished $file_name*********************" >> $error_file
  echo "***********************************************************" >> $error_file

  exit 1
fi
